### ISSUE TITLE
Error: HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by anibal-aguila** [signcl/docusaurus-prince-pdf#1]
Hi I get the following error

Error: HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/home/user/.npm/_npx/85d58867f08057bf/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: undefined,
  timings: {

**Comment by sparanoid** [comment]
You need to provide the base URL of the site you'd like to generate PDF. For examples:

```bash
npx docusaurus-prince-pdf -u https://docusaurus.io/
```

Not:

```bash
npx docusaurus-prince-pdf -u https://docusaurus.io/docs/
```

This package will look for `/docs/` automatically for you.

**Comment by aisensiy** [comment]
But I think https://docusaurus.io/docs/ is better than https://docusaurus.io/ .

**Comment by sparanoid** [comment]
I've [removed](https://github.com/signcl/docusaurus-prince-pdf/commit/9cc3795c9299b2c403885245981232019d811c85) the `scope` option. Now when you pass `https://docusaurus.io/docs/` it will be parsed into origin and pathname automatically. That means the following commands should work:

```bash
# Genreate from https://docusaurus.io/docs/
npx docusaurus-prince-pdf -u https://docusaurus.io/docs/

# Genreate from https://docusaurus.io/docs/cli
npx docusaurus-prince-pdf -u https://docusaurus.io/docs/cli
```

But now when you pass `https://docusaurus.io/` as URL the result will be different from previous version:

```bash
npx docusaurus-prince-pdf -u https://docusaurus.io/
No next link found!
No buffer to write!
```

If you really mean to create a PDF of the Docusaurus home page. You can:

```bash
npx docusaurus-prince-pdf -u https://docusaurus.io/ --include-index
```
