### ISSUE TITLE
Unable to pass extra arguments to Prince

### ISSUE THREAD

**Issue by csant** [signcl/docusaurus-prince-pdf#2]
Hi,
I seem to be unable to pass extra arguments to Prince - specifically, I am trying to  enable JavaScript in Prince, and the switch `--prince-args '--javascript'` doesn't seem to have any effect.

Running
`npx docusaurus-prince-pdf -u http://localhost/doc/ --selector '.docs-next' --prince-args '--javascript'`
on a locally run Docusaurus v1 site.

**Comment by csant** [comment]
Actually, the report is strictly speaking invalid - it **does** take extra arguments, but **they need to be properly escaped**!

Thus, the right command would be:
`npx docusaurus-prince-pdf -u http://localhost/doc/ --selector '.docs-next' --prince-args '\-\-javascript'`

Probably something that should be mentioned in the documentation.

**Comment by sparanoid** [comment]
You can avoid escaping by using:

```
--prince-args='--javascript'
```
