### ISSUE TITLE
Unable to create PDF 

### ISSUE THREAD

**Issue by brmscheiner** [signcl/docusaurus-prince-pdf#3]
I installed prince and docusaurus-prince-pdf, then generated a PDF of the official Docusaurus documentation using the guide in the readme. However attempting to generate a pdf from my site I encountered an error:

```
% npx docusaurus-prince-pdf -u https://docs.wildme.org/docs/developers/codex_overview                                         
Got link: https://docs.wildme.org/docs/developers/houston
...omitting some of these for brevity...
Got link: https://docs.wildme.org/docs/developers/edmapi/site_settings
No next link found!
Writing buffer (11 links) to ./pdf/docs.wildme.org-docs-developers/codex_overview.txt
[Error: ENOENT: no such file or directory, open './pdf/docs.wildme.org-docs-developers/codex_overview.txt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './pdf/docs.wildme.org-docs-developers/codex_overview.txt'
}
```

Based on the error I guessed that maybe it was having trouble finding the css selector for the next button. So I attempted the following: 

```
% npx docusaurus-prince-pdf -u https://docs.wildme.org/docs/developers/codex_overview -s pagination-nav__item--next
No next link found!
No buffer to write!
```

Here is the [source code](https://github.com/wildmeorg/wildme-docs) to our docs, which are generated using Docusaurus `2.0.0-alpha.70`. Thanks for the help!

**Comment by hatton** [comment]
Yeah something must have fallen out of date. Even the sample commands aimed at docusaurus.io now give just

```
$ npx docusaurus-prince-pdf -u https://docusaurus.io/docs/cli
No next link found!
No buffer to write!
```

**Comment by sparanoid** [comment]
@hatton Actually it still works with custom `--selector` option:

```bash
npx docusaurus-prince-pdf -u https://docusaurus.io/docs/ --selector '.pagination-nav__link--next'
```

Sorry for the lack of documentation. I'll update it later.

**Comment by sparanoid** [comment]
Fixed https://github.com/signcl/docusaurus-prince-pdf/actions/runs/2331342677
